//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayOfTheWeekConsoleClient.DayOfWeekServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayOfWeekServiceReference.IDayInBulgaria")]
    public interface IDayInBulgaria {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayInBulgaria/DayOfWeek", ReplyAction="http://tempuri.org/IDayInBulgaria/DayOfWeekResponse")]
        string DayOfWeek(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayInBulgaria/DayOfWeek", ReplyAction="http://tempuri.org/IDayInBulgaria/DayOfWeekResponse")]
        System.Threading.Tasks.Task<string> DayOfWeekAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayInBulgariaChannel : DayOfTheWeekConsoleClient.DayOfWeekServiceReference.IDayInBulgaria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayInBulgariaClient : System.ServiceModel.ClientBase<DayOfTheWeekConsoleClient.DayOfWeekServiceReference.IDayInBulgaria>, DayOfTheWeekConsoleClient.DayOfWeekServiceReference.IDayInBulgaria {
        
        public DayInBulgariaClient() {
        }
        
        public DayInBulgariaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayInBulgariaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayInBulgariaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayInBulgariaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DayOfWeek(System.DateTime date) {
            return base.Channel.DayOfWeek(date);
        }
        
        public System.Threading.Tasks.Task<string> DayOfWeekAsync(System.DateTime date) {
            return base.Channel.DayOfWeekAsync(date);
        }
    }
}
